services:
  app:
    container_name: 999-multibots
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '2999:2999'
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
      - '3004:3004'
      - '3005:3005'
      - '3006:3006'
      - '3007:3007'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BOT_TOKEN_1=${BOT_TOKEN_1}
      - BOT_TOKEN_2=${BOT_TOKEN_2}
      - BOT_TOKEN_3=${BOT_TOKEN_3}
      - BOT_TOKEN_4=${BOT_TOKEN_4}
      - BOT_TOKEN_5=${BOT_TOKEN_5}
      - BOT_TOKEN_6=${BOT_TOKEN_6}
      - BOT_TOKEN_7=${BOT_TOKEN_7}
      - INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
      - INNGEST_URL=${INNGEST_URL}
      - INNGEST_BASE_URL=${INNGEST_BASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ORIGIN=${ORIGIN}
      - ADMIN_IDS=${ADMIN_IDS}
      - SECRET_KEY=${SECRET_KEY}
      - LOG_FORMAT=${LOG_FORMAT}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - DOCKER_ENVIRONMENT=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/nginx:/etc/nginx
      - /etc/pki:/etc/pki
      # - /root/.ssh:/app/.ssh:ro
      # Файлы Ansible
      - ./playbook.yml:/app/playbook.yml:ro
      - ./inventory:/app/inventory:ro
      - ./roles:/app/roles:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "api.elevenlabs.io:127.0.0.1"
      - "host.docker.internal:172.27.0.1"
      - DEBUG=true
      - TS_NODE_PROJECT=tsconfig.prod.json
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: bot-proxy
    ports:
      - '8443:443'
      - '8080:80'
    volumes:
      # Используем нашу кастомную конфигурацию
      - ./nginx-config:/etc/nginx/conf.d:ro
      # Пути к сертификатам с хоста остаются
      - /etc/pki/cert.crt:/etc/pki/cert.crt:ro
      - /etc/pki/key.pem:/etc/pki/key.pem:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16

# Объявляем Docker Volume
volumes:
  nginx-config-volume: 